[package]
name = "twok48"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.25"
wasm-logger = "0.2.0"
web-sys = { version = "0.3.77", features = ["HtmlElement"] }
yew = { version = "0.21.0", features = ["csr", "ssr"] }
getrandom = { version = "0.2", features = ["js"] }
rand = "0.8"